import type { Board, Player, RoundEvent, Vehicle } from '../types/game'
export function GameBoard({board,vehicles,players,currentPlayerId,event}:{board:Board;vehicles:Vehicle[];players:Player[];currentPlayerId:string;event?:RoundEvent}){
 const names=Object.fromEntries(players.map(p=>[p.id,p.name]));
 const fire=event?.type==='FIRE'?event:undefined
 const dx=fire?(fire.newPosition.x-fire.oldPosition.x)/board.width*100:0
 const dy=fire?(fire.newPosition.y-fire.oldPosition.y)/board.height*100:0
 const length=Math.hypot(dx,dy), angle=Math.atan2(dy,dx)*180/Math.PI
 return <div className="board-wrap"><div className="board" role="grid" aria-label="Spelplan" data-testid="game-board" data-width={board.width} data-height={board.height} style={{gridTemplateColumns:`repeat(${board.width}, 1fr)`,aspectRatio:`${board.width}/${board.height}`}}>
  {board.walls.map(w=><div className="wall" data-testid="board-wall" data-x={w.x} data-y={w.y} key={`${w.x}-${w.y}`} style={{left:`${w.x/board.width*100}%`,top:`${w.y/board.height*100}%`,width:`${100/board.width}%`,height:`${100/board.height}%`}} />)}
  {board.pits.map(p=><div className="pit" data-testid="board-pit" data-x={p.x} data-y={p.y} key={`${p.x}-${p.y}`} style={{left:`${p.x/board.width*100}%`,top:`${p.y/board.height*100}%`,width:`${100/board.width}%`,height:`${100/board.height}%`}} />)}
  {fire&&<div className="cannon-fire" data-testid="fire-event" style={{left:`${(fire.oldPosition.x+.5)/board.width*100}%`,top:`${(fire.oldPosition.y+.5)/board.height*100}%`,width:`${length}%`,transform:`rotate(${angle}deg)`}} />}
  {vehicles.map(v=><div className={`vehicle${v.playerId===currentPlayerId?' own-vehicle':''}${event?.type==='HIT'&&event.vehicleId===v.id?' vehicle-hit':''}${event?.type==='DAMAGE'&&event.vehicleId===v.id?' vehicle-damaged':''}${event?.type==='PIT'&&event.vehicleId===v.id?' vehicle-pit':''}`} role="gridcell" aria-label={`${names[v.playerId]} på position ${v.x}, ${v.y}, skada ${v.damage}`} data-testid="player-vehicle" data-player-id={v.playerId} data-player-name={names[v.playerId]} data-x={v.x} data-y={v.y} data-direction={v.direction} data-damage={v.damage} key={v.id} style={{left:`${v.x/board.width*100}%`,top:`${v.y/board.height*100}%`,width:`${100/board.width}%`,height:`${100/board.height}%`}}><span className="vehicle-direction" style={{transform:`rotate(${({NORTH:0,EAST:90,SOUTH:180,WEST:270})[v.direction]}deg)`}}>▲</span><small>{names[v.playerId]} · {v.damage} dmg</small>{event?.type==='HIT'&&event.vehicleId===v.id&&<span data-testid="hit-event" className="impact">HIT</span>}{event?.type==='DAMAGE'&&event.vehicleId===v.id&&<span data-testid="damage-event" className="impact">+{event.newDamage-event.oldDamage}</span>}{event?.type==='PIT'&&event.vehicleId===v.id&&<span data-testid="pit-event" className="impact">PIT</span>}</div>)}
 </div></div>
}
