package se.segersten.wreckage.game.domain;

public enum RoundEventType{VEHICLE_RESPAWNED,MOVE,TURN,RAM,PUSH,CONVEYOR_MOVE,CONVEYOR_RAM,CONVEYOR_PUSH,CONVEYOR_CRASH,ROTATOR_TURN,FIRE,HIT,DAMAGE,CRASH,SCORE_CHANGED}
