package se.segersten.wreckage.game.domain;

public enum RoundEventType{VEHICLE_RESPAWNED,MOVE,TURN,RAM,PUSH,CONVEYOR_MOVE,CONVEYOR_RAM,CONVEYOR_PUSH,CONVEYOR_CRASH,ROTATOR_TURN,CRASH,WEAPON_FIRED,WEAPON_HIT,DAMAGE_APPLIED,VEHICLE_CRASHED,SCORE_CHANGED}
