export type MovementOrder = 'FORWARD_1'|'FORWARD_2'|'REVERSE_1'|'TURN_LEFT'|'TURN_RIGHT'|'U_TURN'|'WAIT'
export type Direction = 'NORTH' | 'EAST' | 'SOUTH' | 'WEST'
export type RoundPhase = 'PLANNING' | 'RESOLVING' | 'PLAYBACK'
export type Player = { id: string; name: string; score: number; visitedCheckpoints: string[]; crashes: number }
export type PlayerJoin = Player & { token: string }
export type GameStatus = 'WAITING_FOR_PLAYERS' | 'RUNNING' | 'FINISHED'
export type GameConfiguration = { maxPlayers: number; joinTimeoutSeconds: number; programSize: number; planningTimeoutSeconds: number; roundLimit: number; checkpointScore: number; crashPenalty: number; pushCrashScore: number }
export type Position = { x: number; y: number }
export type Wall = { cell: Position; direction: Direction }
export type Checkpoint = { id: string; position: Position }
export type SpawnPoint = { position: Position; orientation: Direction }
export type Board = { width: number; height: number; walls: Wall[]; pits: Position[]; checkpoints: Checkpoint[]; spawnPoints: SpawnPoint[] }
export type VehicleStatus = 'ACTIVE' | 'CRASHED'
export type Vehicle = { id: string; playerId: string; x: number; y: number; direction: Direction; damage: number; status: VehicleStatus; spawnPoint: Position; spawnOrientation: Direction }
export type RoundEventType = 'VEHICLE_RESPAWNED' | 'MOVE' | 'TURN' | 'RAM' | 'PUSH' | 'FIRE' | 'HIT' | 'DAMAGE' | 'CRASH' | 'SCORE_CHANGED'
export type ScoreChangeReason = 'CHECKPOINT' | 'CRASH_PENALTY' | 'PUSH_CRASH'
export type RoundEvent = { sequence: number; type: RoundEventType; playerId: string; vehicleId: string; sourcePlayerId: string; sourceVehicleId: string; oldPosition: Position; newPosition: Position; oldDirection: Direction; newDirection: Direction; oldDamage: number; newDamage: number; oldScore?: number; newScore?: number; scoreDelta?: number; scoreReason?: ScoreChangeReason; checkpointId?: string }
export type PublicRound = { number: number; phase: RoundPhase; planningDeadline:string; ready: Record<string, boolean>; initiative: string[]; initialVehicles: Vehicle[]; initialScores: Record<string, number>; startEvents: RoundEvent[]; playback: RoundEvent[] }
export type Placement = { playerId: string; placement: number; score: number; checkpointsVisited: number; crashes: number; winner: boolean }
export type Game = { id: string; status: GameStatus; configuration: GameConfiguration; createdAt: string; joinDeadline: string; players: Player[]; board: Board; vehicles: Vehicle[]; round: PublicRound | null; placements: Placement[] }
export type PlayerGame = Omit<Game, 'round'> & { playerId: string; round: { state: PublicRound; program: MovementOrder[] } | null }
export type PlayerSession = { gameId: string; playerId: string; token: string }
