ALTER TABLE game ADD COLUMN board_checkpoints VARCHAR(20000) NOT NULL DEFAULT '';
ALTER TABLE game ADD COLUMN round_limit INTEGER NOT NULL DEFAULT 6;
ALTER TABLE game ADD COLUMN checkpoint_score INTEGER NOT NULL DEFAULT 2;
ALTER TABLE game ADD COLUMN crash_penalty INTEGER NOT NULL DEFAULT -1;
ALTER TABLE game ADD COLUMN push_crash_score INTEGER NOT NULL DEFAULT 1;
ALTER TABLE game ADD CONSTRAINT chk_game_round_limit CHECK (round_limit > 0);

ALTER TABLE player ADD COLUMN score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN visited_checkpoints VARCHAR(20000) NOT NULL DEFAULT '';

ALTER TABLE game_round ADD COLUMN initial_scores_payload VARCHAR(20000) NOT NULL DEFAULT '';
