CREATE TABLE game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    board_width INTEGER,
    board_height INTEGER,
    CONSTRAINT uq_game_domain_id UNIQUE (domain_id),
    CONSTRAINT chk_game_board_width_positive
        CHECK (board_width IS NULL OR board_width > 0),
    CONSTRAINT chk_game_board_height_positive
        CHECK (board_height IS NULL OR board_height > 0)
);

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id UUID NOT NULL,
    game_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_player_domain_id UNIQUE (domain_id),
    CONSTRAINT fk_player_game
        FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE
);

CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    position_x DOUBLE PRECISION NOT NULL,
    position_y DOUBLE PRECISION NOT NULL,
    direction VARCHAR(50) NOT NULL,
    CONSTRAINT fk_vehicle_player
        FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE
);

CREATE TABLE vehicle_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    segment_index INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL,
    CONSTRAINT fk_vehicle_segment_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE,
    CONSTRAINT uq_vehicle_segment_index UNIQUE (vehicle_id, segment_index)
);

CREATE INDEX idx_player_game_id ON player (game_id);
CREATE INDEX idx_vehicle_player_id ON vehicle (player_id);
