ALTER TABLE game ADD COLUMN map_id VARCHAR(255) NOT NULL DEFAULT 'legacy';
ALTER TABLE game ADD COLUMN map_name VARCHAR(255) NOT NULL DEFAULT 'Legacy';
ALTER TABLE game ADD COLUMN configured_map_id VARCHAR(255);
ALTER TABLE game ADD COLUMN board_obstacles VARCHAR(20000) NOT NULL DEFAULT '';
