ALTER TABLE player ADD COLUMN access_token_hash VARCHAR(64) NOT NULL DEFAULT 'legacy';

ALTER TABLE vehicle ADD COLUMN domain_id UUID;
ALTER TABLE vehicle ADD COLUMN player_domain_id UUID;
ALTER TABLE vehicle ADD COLUMN game_id BIGINT;
ALTER TABLE vehicle ALTER COLUMN player_id DROP NOT NULL;
ALTER TABLE vehicle ADD CONSTRAINT uq_vehicle_domain_id UNIQUE (domain_id);
ALTER TABLE vehicle ADD CONSTRAINT uq_vehicle_player_domain_id UNIQUE (player_domain_id);
ALTER TABLE vehicle ADD CONSTRAINT fk_vehicle_game FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE;

CREATE TABLE game_round (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    phase VARCHAR(20) NOT NULL,
    program_payload VARCHAR(20000) NOT NULL,
    initial_state_payload VARCHAR(20000) NOT NULL,
    playback_payload VARCHAR(30000) NOT NULL,
    CONSTRAINT uq_game_round_game UNIQUE (game_id),
    CONSTRAINT fk_game_round_game FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE,
    CONSTRAINT chk_round_phase CHECK (phase IN ('PROGRAMMING', 'RESOLVING', 'PLAYBACK'))
);
