package se.segersten.wreckage.game.domain;
import static org.assertj.core.api.Assertions.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;
class ProgramPlanningTest{
 @Test void loadoutEligibilityIncludesBothSideStepDirections(){var vehicle=new Vehicle(UUID.randomUUID(),UUID.randomUUID(),new Position(0,0),Direction.NORTH,PrimaryWeapon.REPULSOR,SpecialAbility.SIDE_STEP);assertThat(vehicle.permits(ActionType.REPULSOR)).isTrue();assertThat(vehicle.permits(ActionType.SIDE_STEP_LEFT)).isTrue();assertThat(vehicle.permits(ActionType.SIDE_STEP_RIGHT)).isTrue();assertThat(vehicle.permits(ActionType.LASER)).isFalse();assertThat(vehicle.permits(ActionType.SHIELD)).isFalse();}
 @Test void supportsDraftsDuplicatesLockingAndTimeout(){UUID id=UUID.randomUUID();var p=PlayerProgram.empty(id,3).edit(List.of(MovementOrder.FORWARD_1,MovementOrder.FORWARD_1));var locked=p.lock(List.of(MovementOrder.FORWARD_1,MovementOrder.FORWARD_1,MovementOrder.WAIT));assertThat(locked.ready()).isTrue();assertThatThrownBy(()->locked.edit(List.of())).isInstanceOf(IllegalStateException.class);Instant deadline=Instant.parse("2099-01-01T00:00:00Z");var round=new Round(1,RoundPhase.PLANNING,Map.of(id,p),List.of(id),new GameState(new Board(5,5),List.of()),List.of(),deadline);assertThat(round.completeTimedOutPrograms(deadline)).isTrue();assertThat(round.programs().get(id).commands()).containsExactly(MovementOrder.FORWARD_1,MovementOrder.FORWARD_1,MovementOrder.WAIT);}
 @Test void exposesExactlyTheV2Commands(){assertThat(MovementOrder.values()).containsExactly(MovementOrder.FORWARD_1,MovementOrder.FORWARD_2,MovementOrder.REVERSE_1,MovementOrder.TURN_LEFT,MovementOrder.TURN_RIGHT,MovementOrder.U_TURN,MovementOrder.WAIT);}
 @Test void classifiesActionTimingServerSide(){assertThat(ActionType.values()).filteredOn(a->a.timing()==ActionTiming.PRE_MOVEMENT).containsExactly(ActionType.SHIELD,ActionType.ANCHOR);assertThat(ActionType.values()).filteredOn(a->a.timing()==ActionTiming.POST_MOVEMENT).containsExactly(ActionType.LASER,ActionType.REPULSOR,ActionType.ROCKET,ActionType.TURBO,ActionType.SIDE_STEP_LEFT,ActionType.SIDE_STEP_RIGHT);}
 @Test void schedulesChangesAndClearsOneActionBeforeLock(){UUID id=UUID.randomUUID();var laser=new ScheduledAction(ActionType.LASER,2);var repulsor=new ScheduledAction(ActionType.REPULSOR,3);var program=PlayerProgram.empty(id,3).schedule(laser);assertThat(program.scheduledAction()).isEqualTo(laser);program=program.schedule(repulsor);assertThat(program.scheduledAction()).isEqualTo(repulsor);program=program.schedule(null);assertThat(program.scheduledAction()).isNull();assertThat(program.lock(List.of(MovementOrder.WAIT,MovementOrder.WAIT,MovementOrder.WAIT)).scheduledAction()).isNull();}
 @Test void validatesActionRegisterAndLocksTheCompletePlan(){UUID id=UUID.randomUUID();assertThatThrownBy(()->PlayerProgram.empty(id,3).schedule(new ScheduledAction(ActionType.LASER,4))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new ScheduledAction(ActionType.LASER,0)).isInstanceOf(IllegalArgumentException.class);var locked=PlayerProgram.empty(id,3).lock(List.of(MovementOrder.WAIT,MovementOrder.WAIT,MovementOrder.WAIT),new ScheduledAction(ActionType.SHIELD,1));assertThatThrownBy(()->locked.schedule(null)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->locked.edit(List.of())).isInstanceOf(IllegalStateException.class);}
 @Test void timeoutPreservesAnExplicitAction(){UUID id=UUID.randomUUID();Instant deadline=Instant.parse("2099-01-01T00:00:00Z");var action=new ScheduledAction(ActionType.ANCHOR,2);var program=PlayerProgram.empty(id,3).schedule(action);var round=new Round(1,RoundPhase.PLANNING,Map.of(id,program),List.of(id),new GameState(new Board(5,5),List.of()),List.of(),deadline);round.completeTimedOutPrograms(deadline);assertThat(round.programs().get(id).scheduledAction()).isEqualTo(action);assertThat(round.programs().get(id).ready()).isTrue();}
}
