spring.application.name=wreckage
spring.jpa.hibernate.ddl-auto=validate
wreckage.cards.weights.forward-1=20
wreckage.cards.weights.forward-2=15
wreckage.cards.weights.forward-3=10
wreckage.cards.weights.backward-1=10
wreckage.cards.weights.turn-left=15
wreckage.cards.weights.turn-right=15
wreckage.cards.weights.u-turn=5
